### ISSUE TITLE
Unable to open menu bar items using jbr17_0_2b315.1

### ISSUE THREAD

**Issue by korthout** [JetBrains/JetBrainsRuntime#112]
The top menu bar mostly doesn't show the dropdown items in IntelliJ when using the latest JBR release.

The standard app menu item works correctly:
<img src="https://user-images.githubusercontent.com/3511026/153565046-18d91e57-18da-434a-829f-5dd1b3f02060.png" width=50% height=50%>

App-specific menu items don't open a dropdown
<img src="https://user-images.githubusercontent.com/3511026/153565043-313fb564-f55f-4608-9553-ef4bd42e7972.png" width=50% height=50%>

The help menu item only shows the search bar
<img src="https://user-images.githubusercontent.com/3511026/153565033-d7ce7ad8-64ff-4a2f-8cb4-66b8f9ed0db0.png" width=50% height=50%>

No app-specific menu items show a dropdown, this is also the case when a project is open
<img src="https://user-images.githubusercontent.com/3511026/153566191-62122b68-67af-45ef-a7d7-c35b955164d3.png" width=50% height=50%>

Version info
<img src="https://user-images.githubusercontent.com/3511026/153565835-49f3a532-b1e7-49f5-a11c-9567280d341e.png" width=50% height=50%>

**Comment by sy2nyk** [comment]
https://github.com/JetBrains/JetBrainsRuntime/issues/110
`--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED`

**Comment by fyeeme** [comment]
with jbr17_0_2b, idea generate error with log below :

```log
cannot load from prebuilt icon cache

java.lang.IllegalAccessError: class com.intellij.ui.svg.SvgCacheManager$Companion (in unnamed module @0x3fbcb3e8) cannot access class sun.awt.image.SunWritableRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x3fbcb3e8
	at com.intellij.ui.svg.SvgCacheManager$Companion.readImage(SvgCacheManager.kt:53)
	at com.intellij.ui.svg.SvgPrebuiltCacheManager.loadFromCache(SvgPrebuiltCacheManager.kt:79)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.java:149)
	at com.intellij.ui.RasterizedImageDataLoader.loadRasterized(RasterizedImageDataLoader.java:210)
	at com.intellij.ui.RasterizedImageDataLoader.loadImage(RasterizedImageDataLoader.java:91)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:958)
	at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1027)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:846)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconWidth(IconLoader.java:774)
	at com.intellij.util.ui.AsyncProcessIcon.calcPreferredSize(AsyncProcessIcon.java:42)
	at com.intellij.util.ui.AnimatedIcon.<init>(AnimatedIcon.java:38)
	at com.intellij.util.ui.AsyncProcessIcon.<init>(AsyncProcessIcon.java:37)
	at com.intellij.util.ui.AsyncProcessIcon.<init>(AsyncProcessIcon.java:33)
	at com.intellij.idea.ApplicationLoader$prepareStart$4$5.run(ApplicationLoader.kt:258)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by korthout** [comment]
> #110 `--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED`

Adding this to my vm-options fixed it for me. Thanks 🙇

**Comment by sy2nyk** [comment]
@fyeeme try add `--add-opens=java.desktop/sun.awt.image=ALL-UNNAMED`

**Comment by fyeeme** [comment]
Yeah. it's sovled , ths. @sy2nyk
