### ISSUE TITLE
Crash on wayland

### ISSUE THREAD

**Issue by m00ga** [JetBrains/JetBrainsRuntime#337]
System info:
I'm using tag jb21.0.2-b397(built with wayland support) of jbr21 branch and PhpStorm 2024.1 Beta  Build #PS-241.14494.28, and sway WM.
I'm on Linux, aarch64, Asahi Linux Fedora distro with latest GPU drivers, and latest sway release.
Here my vmoptions:
`-Dsun.java2d.opengl=true \
-Dsun.java2d.opengl.fbobject=false \
-ea \
-Dawt.toolkit.name=WLToolkit \
-Xmx2048m`

Problem:
When i hover above anything in dropdown from Help in toolbar, and switch to another workspace, crash happens.
When crash happens java instance doesn't get killed, and this message appears in log: `SEVERE - #c.i.o.a.i.ApplicationImpl - Failed to destruct the application`
There are log of crash:
`xdg_surface@52: error 3: xdg_surface has never been configured
2024-03-11 21:49:24,141 [  12237] SEVERE - sun.awt.wl.WLToolkit - Wayland protocol I/O error
2024-03-11 21:49:24,163 [  12259] SEVERE - #c.i.i.p.PluginManager - Wayland display error flushing data out to the server
java.awt.AWTError: Wayland display error flushing data out to the server
	at java.desktop/sun.awt.wl.WLToolkit.flushImpl(Native Method)
	at java.desktop/sun.awt.wl.WLToolkit.sync(WLToolkit.java:1015)
	at java.desktop/sun.awt.wl.WLComponentPeer.commitToServer(WLComponentPeer.java:395)
	at java.desktop/sun.awt.wl.WLWindowPeer.updateWindow(WLWindowPeer.java:163)
	at java.desktop/sun.awt.wl.WLDecoratedPeer.updateWindow(WLDecoratedPeer.java:94)
	at java.desktop/java.awt.Window.updateWindow(Window.java:3966)
	at java.desktop/java.awt.Window$2.updateWindow(Window.java:4464)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1352)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1110)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3990)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.kt:123)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:889)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1912)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:698)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:393)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)`

**Comment by mkartashev** [comment]
Please check if this looks like a previously reported issue here: https://github.com/JetBrains/JetBrainsRuntime/pull/323/
If so, it is being tracked as [JBR-6763](https://youtrack.jetbrains.com/issue/JBR-6763) Wayland: application crashes when popup closed

**Comment by m00ga** [comment]
> Please check if this looks like a previously reported issue here: #323 If so, it is being tracked as [JBR-6763](https://youtrack.jetbrains.com/issue/JBR-6763) Wayland: application crashes when popup closed

Yep, that's a same issue and error, so i guess, i need close this one

**Comment by mkartashev** [comment]
Duplicate of https://github.com/JetBrains/JetBrainsRuntime/pull/323 / [JBR-6763](https://youtrack.jetbrains.com/issue/JBR-6763), closing.
