### ISSUE TITLE
Can JBR 17 used to run PyCharm?

### ISSUE THREAD

**Issue by nihil-admirari** [JetBrains/JetBrainsRuntime#87]
`--illegal-access=permit` was removed from Java 17. I've added the following lines to `pycharm64.vmoptions`:
```
--add-opens=java.desktop/sun.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt.event=ALL-UNNAMED
--add-opens=java.desktop/sun.swing=ALL-UNNAMED
--add-opens=java.desktop/javax.swing=ALL-UNNAMED
--add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED
```
but PyCharm CE 2021.2 still refuses to start:
```
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
2021-09-30 19:14:00,290 [   3628]   WARN - tor.impl.FontFamilyServiceImpl - Couldn't access required runtime API, will fall back to basic logic of font selection 
2021-09-30 19:14:00,620 [   3958]   WARN - nSystem.impl.ActionManagerImpl - keymap "Visual Studio" not found [Plugin: com.intellij] 
2021-09-30 19:14:00,625 [   3963]   WARN - nSystem.impl.ActionManagerImpl - keymap "Eclipse" not found [Plugin: com.intellij] 
2021-09-30 19:14:00,689 [   4027]   WARN - nSystem.impl.ActionManagerImpl - keymap "NetBeans 6.5" not found [Plugin: com.intellij] 
2021-09-30 19:14:00,690 [   4028]   WARN - nSystem.impl.ActionManagerImpl - keymap "Visual Studio" not found [Plugin: com.intellij] 
2021-09-30 19:14:00,745 [   4083]   WARN - nSystem.impl.ActionManagerImpl - keymap "Eclipse" not found [Plugin: org.jetbrains.plugins.github] 
2021-09-30 19:14:00,773 [   4111]   WARN - nSystem.impl.ActionManagerImpl - keymap "Eclipse" not found [Plugin: PythonCore] 
2021-09-30 19:14:00,774 [   4112]   WARN - nSystem.impl.ActionManagerImpl - keymap "NetBeans 6.5" not found [Plugin: PythonCore] 
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class com.intellij.openapi.util.objectTree.ThrowableInterner
	at com.intellij.idea.IdeaLogger.isTooFrequentException(IdeaLogger.java:91)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:188)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:208)
	at com.intellij.ide.plugins.StartupAbortedException.processException(StartupAbortedException.java:31)
	at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.java:621)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:450)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
An "Import PyCharm Settings" window is shown, but "Do not import settings" results in the above error.

**Comment by System0x40** [comment]
Same problem with a TCK-certified Adoptium 17+35 build.
Why IntelliJ uses such APIs in the first place?
How hard is it for a company with ~£200M worth of revenue to adapt with JPMS and replace sun.awt imports with java.awt ones?

**Comment by nihil-admirari** [comment]
Adding [additional opens and exports](https://github.com/JetBrains/JetBrainsRuntime/issues/90#issuecomment-945307168) allows PyCharm to start:
```
--add-opens=java.desktop/java.awt.event=ALL-UNNAMED
--add-opens=java.desktop/sun.font=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/sun.awt=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.desktop/javax.swing=ALL-UNNAMED
--add-opens=java.desktop/sun.swing=ALL-UNNAMED
--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
--add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED
--add-exports=java.desktop/sun.font=ALL-UNNAMED
--add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED
--add-exports=java.desktop/com.apple.laf=ALL-UNNAMED
--add-exports=java.desktop/com.apple.eawt.event=ALL-UNNAMED
```
