### ISSUE TITLE
Webstorm cannot launch

### ISSUE THREAD

**Issue by LifeIsStrange** [JetBrains/JetBrainsRuntime#99]
I have tried to set your custom JDK latest release
 jbr_jcef-17_0_1-linux-x64-b164.8.tar.gz
https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr17_0_1b164.8

Should I use jbrsdk_jcef-17_0_1-linux-x64-b164.8.tar.gz instead?
I'm on archlinux, dependencies up to date.

```
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

com.intellij.ide.plugins.StartupAbortedException: UI initialization failed
    at com.intellij.idea.StartupUtil.lambda$start$15(StartupUtil.java:268)
    at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
    at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
    at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:777)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:747)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
    at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
    ... 14 more
Caused by: java.lang.ExceptionInInitializerError
    at com.intellij.icons.AllIcons$Nodes.<clinit>(AllIcons.java:716)
    at com.intellij.ide.ui.laf.IdeaLaf.initIdeaDefaults(IdeaLaf.java:74)
    at com.intellij.ide.ui.laf.IdeaLaf.initComponentDefaults(IdeaLaf.java:35)
    at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:153)
    at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1566)
    at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$21(StartupUtil.java:475)
    at com.intellij.ui.scale.JBUIScale.computeSystemFontData(JBUIScale.java:69)
    at com.intellij.ui.scale.JBUIScale.getSystemFontData(JBUIScale.java:360)
    at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$22(StartupUtil.java:473)
    at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
    ... 14 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.awt.Font.getSize()" because "font" is null
    at com.intellij.ui.scale.JBUIScale.computeSystemFontData(JBUIScale.java:91)
    at com.intellij.ui.scale.JBUIScale.getSystemFontData(JBUIScale.java:360)
    at com.intellij.ui.scale.JBUIScale.computeSystemScaleFactor(JBUIScale.java:163)
    at com.intellij.ui.scale.JBUIScale.sysScale(JBUIScale.java:283)
    at com.intellij.ui.scale.JBUIScale.getOrComputeUserScaleFactor(JBUIScale.java:190)
    at com.intellij.ui.scale.JBUIScale.scale(JBUIScale.java:314)
    at com.intellij.ui.scale.UserScaleContext.<init>(UserScaleContext.java:26)
    at com.intellij.util.ui.JBUI$BaseScaleContext.<init>(JBUI.java:1408)
    at com.intellij.ui.scale.ScaleContext.<init>(ScaleContext.java:32)
    at com.intellij.ui.scale.ScaleContext.create(ScaleContext.java:108)
    at com.intellij.ui.scale.ScaleContextSupport.<init>(ScaleContextSupport.java:11)
    at com.intellij.openapi.util.IconLoader$CachedImageIcon.<init>(IconLoader.java:702)
    at com.intellij.ui.CoreIconManager$IconWithToolTipImpl.<init>(CoreIconManager.java:91)
    at com.intellij.ui.CoreIconManager.loadRasterizedIcon(CoreIconManager.java:61)
    at com.intellij.icons.AllIcons.load(AllIcons.java:17)
    at com.intellij.icons.AllIcons.<clinit>(AllIcons.java:667)
    ... 24 more

-----
Your JRE: 17.0.1+12-b164.8 amd64 (JetBrains s.r.o.)
/home/stephane/jbr
```

```
!bootstrap.error.message.internal.error.please.refer.to.0!https://jb.gg/ide/critical-startup-errors!

java.lang.IllegalAccessError: class com.intellij.idea.StartupUtil (in unnamed module @0x342859d0) cannot access class sun.awt.AWTAutoShutdown (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x342859d0
    at com.intellij.idea.StartupUtil.start(StartupUtil.java:300)
    at com.intellij.idea.Main.bootstrap(Main.java:133)
    at com.intellij.idea.Main.main(Main.java:81)
```

**Comment by LifeIsStrange** [comment]
I wonder if that's related to JBR-2135 Use CoreText api to select the font with the most recent version.
(note that I've not used your build process (makefile/docker) and used the release dowload as is.

**Comment by LifeIsStrange** [comment]
@JB-Dmitry

**Comment by gjw0813** [comment]
Same on windows 10 in Clion 2021.3.3

**Comment by gjw0813** [comment]
> Same on windows 10 in Clion 2021.3.3
> 
> ```
> !bootstrap.error.message.internal.error.please.refer.to.0!https://jb.gg/ide/critical-startup-errors!
> 
> java.lang.IllegalAccessError: class com.intellij.idea.StartupUtil (in unnamed module @0x73e14632) cannot access class sun.awt.AWTAutoShutdown (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x73e14632
>     at com.intellij.idea.StartupUtil.start(StartupUtil.java:301)
>     at com.intellij.idea.Main.bootstrap(Main.java:134)
>     at com.intellij.idea.Main.main(Main.java:82)
> 
> -----
> !bootstrap.error.message.jre.details!17.0.2+8-b315.1 amd64 (JetBrains s.r.o.)
> D:\jbr!
> ```

fixed by https://github.com/JetBrains/JetBrainsRuntime/issues/101#issuecomment-1002996786
